### ISSUE TITLE
Add footer to inner landing pages.

### ISSUE THREAD

**Issue by apainintheneck** [apainintheneck/SQL-Study#23]
What do you guys think about adding the footer in a card below the content on the /dashboard, /lecture, and /quizzes pages? It wouldn't be hard to implement at all. The question is whether that's the place the put it and we think it goes best there.

**Comment by harsandeep1** [comment]
Hi Team, I have added the footer on the inner pages. Would you please take a look and let me know if it is working as expected? I had to change the color to #48B4E9, the same color as the four links on the index page [before the hover effect].

**Comment by harsandeep1** [comment]
I created a new branch named `Deep-footer-issueFix-branch.`
