### ISSUE TITLE
Lection section doesn't fill whole screen space

### ISSUE THREAD

**Issue by brycerandolph** [apainintheneck/SQL-Study#24]
The way the lecture section is set up, the content doesn't expand to fill the whole white area

![image](https://user-images.githubusercontent.com/33710291/142801897-46f8c232-1746-4b27-bb9a-b433613a7e63.png)

**Comment by apainintheneck** [comment]
> At the moment, the chapter.ejs page works but it doesn't look that great. The biggest issue is that the images and videos bleed out of the content container. Also, do we want it to look more like the dashboard.ejs page? I think at the very least we should have the content be in a container that doesn't bleed and have the title centered and in a bigger font at the top with a break between it and the rest of the text.

I think this essentially will come down to updating the container html and styles. It probably requires looking at what container is being used in the chapter.ejs page and doing a bit of bootstrap research. Essentially you want a wider default container, right?

**Comment by brycerandolph** [comment]
Exactly, I want the content of the lectures to fill the whole page, which would mean increasing the width of that card element they are sitting on.
