### ISSUE TITLE
Either Create an about page or remove it from the index page navbar

### ISSUE THREAD

**Issue by brycerandolph** [apainintheneck/SQL-Study#33]
Currently, there is a dead link to an /about page. in the top navbar of the index. This issue could be extended to generally restyling the top bar on the index page.

**Comment by apainintheneck** [comment]
I believe that @jeanniedavis mentioned something about the about page before but I don't know if she actually ended up working on it at all.

**Comment by jeanniedavis** [comment]
this is complete!

**Comment by brycerandolph** [comment]
I linked it to your pull request so this issue will be closed when that branch is merged in.
