### ISSUE TITLE
Sandbox Section: Red Error Message remaining on screen indefinitely

### ISSUE THREAD

**Issue by brycerandolph** [apainintheneck/SQL-Study#35]
![image](https://user-images.githubusercontent.com/33710291/143782720-f48f8def-17d2-4438-8e85-0667dff25669.png)
As seen here, even after fixing and re-executing, the message stays on screen.

**Comment by apainintheneck** [comment]
I can try to fix this. It shouldn't be too hard.

**Comment by apainintheneck** [comment]
Bug's been fixed.
