### ISSUE TITLE
Extra Feature

### ISSUE THREAD

**Issue by brycerandolph** [apainintheneck/SQL-Study#37]
Dropdown menus for sidebar that expand to show quizzes 1-4 and lectures 1-4 for quick navigation.

**Comment by apainintheneck** [comment]
I think this is one of those features that sounds nice at first but would quickly get unwieldy if we decided to add more content in the future. Have you seen how crowded the sidebars are on other learning websites?

**Comment by brycerandolph** [comment]
This is a good point, and I will close this now.
