### ISSUE TITLE
Small Bug? in Sandbox

### ISSUE THREAD

**Issue by brycerandolph** [apainintheneck/SQL-Study#42]
While testing today, the tester and I noticed that the final line did not require a semicolon to run properly. Missing a semi-colon anywhere else throws an error.

**Comment by apainintheneck** [comment]
I think that's how SQL works normally when you batch a set of queries.

**Comment by apainintheneck** [comment]
Yeah, I think it's just that semicolons are normally used to define the boundaries between queries so one isn't absolutely necessary at the end.
